# Generated by Django 5.2.14 on 2026-06-01 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_genre_movie_language_alter_theater_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='trailer_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('Action', 'Action'), ('Comedy', 'Comedy'), ('Drama', 'Drama'), ('Horror', 'Horror'), ('Sci-Fi', 'Sci-Fi'), ('Romance', 'Romance'), ('Thriller', 'Thriller'), ('Animation', 'Animation'), ('Documentary', 'Documentary'), ('Sports', 'Sports'), ('Family', 'Family'), ('Fantasy', 'Fantasy')], db_index=True, default='null', max_length=100),
        ),
    ]
